### ISSUE TITLE
What is the file "CryptoJS.HmacSHA256.gs" gor?

### ISSUE THREAD

**Issue by howardpen9** [jadewon/s3-http-post-gs#3]
Hi, I check the data but can't understand what is it for. Can you explain?

**Comment by jadewon** [comment]
Hi, @howardpen9 
CryptoJS basically for generating s3 signature.

https://github.com/jadewon/s3-http-post-gs/blob/fe1f4862313cd4b632cf4bb4037574ada5eb10c4/S3HttpPost.gs#L52-L59

**Comment by howardpen9** [comment]
thanks for your reply!
